feat: [P4PU-628] added tf scripts for allarm
pagopa/arc-infra pull request #45
Opened 2024-10-29 08:26 UTC by oleksiybozhykntt

### List of changes
added tf scripts for allarm

### Motivation and context

### Type of changes

- [ ] Add new resources
- [ ] Update configuration to existing resources
- [ ] Remove existing resources

### Env to apply

- [ ] DEV
- [ ] UAT
- [ ] PROD

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [ ] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [ ] No

### Other information

---

### If PR is partially applied, why? (reserved to mantainers)

2024-10-30 15:01 UTC, antonioT90 requested changes

2024-10-30 15:43 UTC, oleksiybozhykntt commented on src/06_domains/cittadini-app/00_keyvault.tf
removed

2024-10-30 15:43 UTC, oleksiybozhykntt commented on src/06_domains/cittadini-app/00_data.tf
> +  resource_group_name = var.log_analytics_workspace_resource_group_name
updated with locals and removed varibales

2024-10-30 15:50 UTC, antonioT90 requested changes

2024-10-30 15:50 UTC, antonioT90 commented on src/06_domains/cittadini-app/99_locals.tf
> +  azurerm_log_analytics_workspace_log_analytics_resource_group_name = "${local.project_core}-monitor-rg"
let's keep simpler these names
```suggestion
  log_analytics_name = "${local.project_core}-law"
  log_analytics_resource_group_name = "${local.project_core}-monitor-rg"
```

2024-10-30 15:50 UTC, antonioT90 commented on src/06_domains/cittadini-app/99_locals.tf
> +  azurerm_log_analytics_workspace_log_analytics_resource_group_name = "${local.project_core}-monitor-rg"
moreover, the monitor resource group is already referenced:
see data.azurerm_resource_group.monitor_rg"

2024-10-30 15:50 UTC, antonioT90 commented on src/06_domains/cittadini-app/99_variables.tf
> +variable "arc_alert_enabled" {
in UAT  environment configuration this should be true (src/06_domains/cittadini-app/env/itn-uat/terraform.tfvars)

2024-10-30 16:03 UTC, antonioT90 approved these changes

2024-10-30 16:08 UTC, umbcoppolabottazzi commented on src/06_domains/cittadini-app/12_alert.tf
> +resource "azurerm_monitor_action_group" "slackArc" {
Please change the resource name to kebab case

2024-10-30 16:11 UTC, umbcoppolabottazzi commented on src/06_domains/cittadini-app/12_alert.tf
> +resource "azurerm_monitor_action_group" "slackArc" {
```suggestion
resource "azurerm_monitor_action_group" "slack_cittadini" {
```

2024-10-30 16:11 UTC, umbcoppolabottazzi commented on src/06_domains/cittadini-app/12_alert.tf
> +  name                = "SlackArc"
```suggestion
  name                = "slack-${var.domain}"
```

2024-10-31 09:06 UTC, umbcoppolabottazzi commented
Great Job!

2024-10-31 09:07 UTC, umbcoppolabottazzi approved these changes

2024-10-31 09:08 UTC, merged